#[[redirects]]
#from = "/netlify/anything"
#to = "https://www.google.com/search?q=anything"
#status = 301
#force = false

#[[redirects]]
#from = "/search"
#to = "https://google.com/search?q=stuff"
#status = 200
#proxy = true
#pattern = "^/proxy(?:|/|(.*)/?)$"

#[[redirects]]
#from = "/blog"
#to = "brave-brattain-2a4c10.netlify.app"
#status = 200

[[redirects]]
  from = "/blog"
  to = "https://brave-brattain-2a4c10.netlify.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
