[[redirects]]
from = "/netlify/anything"
to = "https://www.google.com/search?q=anything"
status = 301
force = false

[[redirects]]
from = "/search"
to = "https://google.com/search?q=stuff"
status = 200
proxy = true
pattern = "^/proxy(?:|/|(.*)/?)$"
  
